export const meta = {
  path: '/about/',
  title: 'About Kensington Bathrooms | Nicholas and Our Local Story',
  description: 'Meet Nicholas, the tradesperson behind Kensington Bathrooms. School near The Little Boltons, childhood visits around Kensington, family ties to Chelsea and decades of plumbing experience.',
  schemaType: 'AboutPage',
  breadcrumbs: [{ name: 'Home', path: '/' }, { name: 'About', path: '/about/' }]
};

export function render(cfg) {
  return `<section class="page-hero page-hero--compact"><div class="page-hero__inner"><p class="eyebrow">The person behind the work</p><h1>Local roots. Bathrooms built with care.</h1><p class="page-hero__lede">Kensington Bathrooms is led by Nicholas. He brings decades of hands-on plumbing and renovation experience to homes across the area where he grew up.</p></div></section>
<section class="content-band content-band--ink"><div class="section-shell story-layout"><div><p class="eyebrow">Nicholas's story</p><h2>These streets have been part of my life for a long time.</h2></div><div class="content-copy"><p>I grew up around Kensington and Chelsea and went to Bousfield Primary School on South Bolton Gardens, close to The Little Boltons. I was in this area every school day, and as a child I visited friends' houses in The Little Boltons and around Kensington. Seeing those homes sparked my interest in buildings and architecture: how different houses were laid out, how they had changed over time and what made each one feel distinctive.</p><p>My family's connection to the area goes back further. My parents met at the Black Bull. They later married in Chelsea. We used to eat at the Chelsea Kitchen when it was open. These are places I knew growing up. Years later, when I began working in plumbing and bathrooms, that interest in homes became part of the way I approached the work.</p><p>I started plumbing in 1998, following a family background in building work. Since then I've worked with the services and construction behind bathrooms as well as the fittings you see when a room is finished. I know that the first conversation is usually about what you would like to change, and whether the room and the building will let us do it properly.</p><p>That is why I come to see the property. We can talk through a different layout, a better shower, the boiler and hot-water supply, tiles, ventilation and the practical route into the room. I will tell you what looks possible, what needs checking and where a decision depends on the building or its managing agent.</p></div></div></section>
<section class="content-band content-band--deep"><div class="section-shell"><div class="content-grid"><div><p class="eyebrow">How I work with you</p><h2>Start with a conversation in the room.</h2></div><div class="content-copy"><p>You do not need to arrive with a final design or know which fittings will work. Show me what bothers you about the existing bathroom and what you would love to change. We look at the available space and the less visible things that can affect the result: water and waste routes, the floor and walls, heating and ventilation, plus access and building rules where relevant.</p><p>From there we can develop a bathroom that suits your home and the way you use it. The design and the installation are considered together, so attractive ideas are checked against what can actually be built.</p><a class="arrow-link" href="/bathroom-renovation/">How a bathroom project takes shape</a></div></div></div></section>
<section class="content-band content-band--ink"><div class="section-shell"><div class="content-grid"><div><p class="eyebrow">Kensington Bathrooms</p><h2>A focused local service.</h2></div><div class="content-copy"><p>We work in Kensington, West Kensington, Holland Park, South Kensington and Chelsea. It is a compact area, close to our local base, so the website can speak plainly about the homes and the people we serve.</p><p>Kensington Bathrooms is the bathroom-focused trading name of ${cfg.company.legalName}. Your enquiry and project are handled through the same company, with one team responsible for the work.</p><a class="arrow-link" href="/contact/">Talk through your bathroom</a></div></div></div></section>`;
}
