export const meta={path:'/privacy/',title:'Privacy | Kensington Bathrooms',description:'Privacy information for Kensington Bathrooms.',schemaType:'WebPage'};
export function render(cfg){return `<article class="legal-page"><p class="eyebrow">Legal</p><h1>Privacy notice</h1>
<p>${cfg.brand.name} is a trading name of ${cfg.company.legalName} (company ${cfg.company.companyNumber}), which is the controller of the personal information described in this notice. Public phone, WhatsApp and email details will be added before launch. Home consultations, or design meetings by appointment at our base in West Kensington.</p>
<h2>Information we collect</h2><p>When you contact us we may collect your name, telephone number, email address, property postcode, project details, photographs you choose to send, appointment information and correspondence about the proposed or active project. If you become a customer, we may also keep quotation, contract, invoice and payment records.</p>
<h2>Why we use it and our lawful basis</h2><p>We use enquiry information to respond to you, discuss the work and arrange a consultation. We rely on our legitimate interests in responding to genuine business enquiries and, where you ask us to take steps before entering a contract or we have a contract with you, on the contractual lawful basis. We do not use enquiry information for unrelated marketing without a separate lawful basis.</p>
<h2>Who receives the information</h2><p>Information is shared only where needed to run the business or deliver the project, for example with relevant members of the project team, professional advisers, IT or communications providers, payment or accounting providers, or authorities where the law requires it. If you choose WhatsApp, WhatsApp or Meta processes information under its own privacy terms.</p>
<h2>Website hosting and analytics</h2><p>The website is hosted using GitHub Pages, whose infrastructure may process technical server information needed to deliver the site. No analytics or advertising provider is enabled in the current build.</p>
<h2>How long we keep information</h2><p>We keep personal information only for as long as it is needed for the enquiry or project and for any legal, accounting, warranty or dispute-resolution obligations that apply afterwards. The retention period therefore depends on the type of record and whether an enquiry becomes a project.</p>
<h2>Your rights</h2><p>Depending on the circumstances, UK data-protection law may give you rights to ask for access to your personal information, correction, deletion, restriction, portability, or to object to processing based on legitimate interests. Where processing is based on consent, you can withdraw that consent.</p>
<h2>Complaints</h2><p>Please contact us first if you have a privacy concern so we can try to resolve it. You also have the right to complain to the UK Information Commissioner’s Office.</p>
<h2>Local base</h2><p>Our local base is 33 Gunterstone Road, London W14 9BP, for design meetings by appointment.</p>
</article>`;}
